const departmentsForAssignment = [
  'General Feedback',
  'Anesthesiology',
  'Cardiology',
  'Dermatology',
  'Internal Medicine',
  'Obstetrics and Gynecology (OB-GYNE)',
  'Pediatrics',
  'Radiology',
  'Rehabilitation Medicine',
  'Surgery',
  'Pathology',
  'Urology',
  'Nephrology',
  'Orthopedics',
  'Ophthalmology',
  'ENT (Ear, Nose, Throat)',
  'Family Medicine',
  'BESTHEALTH',
  'Dental Clinic',
  'Diagnostics',
  'Dietary',
  'Emergency Room (ER)',
  'Hemodialysis',
  'Intensive Care Unit (ICU)',
  'Inpatient Department',
  'Neonatal ICU (NICU)',
  'Nursing Service',
  'Operating Room',
  'Outpatient Department',
  'Pharmacy',
  'Physical Therapy'
];

export default departmentsForAssignment;